[build]
  # Указываем, где лежат исходники фронтенда
  base = "frontend"
  # Команда для сборки внутри папки frontend
  command = "npm run build"
  # Папка, которую Netlify должен выложить в интернет
  publish = "dist"

[[redirects]]
  # Это исправит ошибку 404 при обновлении страницы, если у тебя есть роутинг (Vue Router)
  from = "/*"
  to = "/index.html"
  status = 200