server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Dragon!55
spring.datasource.driver-class-name=org.postgresql.Driver
# JWT
jwt.secret=SGVsbG9Xb3JsZFNwcmluZ0Jvb3RQcm9qZWN0Tm93SXNNeVNlY3JldEtleQ==
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect