server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# JWT
jwt.secret=SGVsbG9Xb3JsZFNwcmluZ0Jvb3RQcm9qZWN0Tm93SXNNeVNlY3JldEtleQ==
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect